use customer_behavior;

select * from customer;

-- Q1. What are the total revenue generated by male vs female customers?
SELECT 
	gender,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- 2. Which customers used a discount but still spent more than the average purchase ammount?
select 
	customer_id,
    purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount));

-- 3. Which are the top 5 products with the highest average review ratings?
 select 
	item_purchased,
    round(avg(review_rating), 2) as average_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5;

-- 4. Compare the average purchase ammounts between standard and express shipping.
select 
	shipping_type,
	round(avg(purchase_amount), 2) as avg_purchase_amount
from customer
where shipping_type IN ('Standard', 'Express') 
group by shipping_type;

-- 5. DO subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select 
	subscription_status,
    count(customer_id) as total_customers,
    round(avg(purchase_amount), 2) as avg_spend,
    sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

-- 6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment
with customer_type as(
	select customer_id, previous_purchases,
    CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal' 
        END AS customer_segment
	FROM customer
)
-- select * from customer_type;
select 
	customer_segment,
    count(previous_purchases) as nubmer_of_customers
from customer_type
group by customer_segment;

-- 8. What are the top 3 most purchased products within each category?
 with top_purchases as (
	select category,
		item_purchased,
        count(customer_id) as total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) as item_rank
	from customer
    group by category, item_purchased
 )
 select item_rank,
		category,
		item_purchased,
        total_orders
 from top_purchases 
 where item_rank <=3;
 
 -- 9. Are customers who are repeate buyers(more than 5 previous purchases) also likely to subscribe?
select COUNT(customer_id) as repeate_buyers,
		CASE WHEN subscription_status = 'Yes' THEN 'Yes'
        ELSE 'No' END AS subscription_status
from customer
where previous_purchases > 5
group by subscription_status
order by repeate_buyers desc;

-- 10. What is the revenue contribution of each age group?
select age_group,
	sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;